#!/bin/bash

function join_by {
    local d=$1
    shift
    echo -n "$1"
    shift
    printf "%s" "${@/#/$d}"
}

PROJECT_IDS=(ES)
GREP_PROJECT_IDS=$(join_by '-\|' ${PROJECT_IDS[*]})-  # append a "-" to the last item
SED_PROJECT_IDS="\($GREP_PROJECT_IDS\)"

ISSUE_ID=$(git symbolic-ref HEAD | awk '{print toupper($0)}' | sed "s/.*\($SED_PROJECT_IDS[0-9]*\).*/\1/")

if echo $ISSUE_ID | grep $GREP_PROJECT_IDS; then
    ISSUE_ID_IN_COMMIT=$(grep -c "$ISSUE_ID" $1)
    if [ -n "$ISSUE_ID" ] && ! [[ $ISSUE_ID_IN_COMMIT -ge 1 ]]; then
        sed -i.bak -e "1s/^/[$ISSUE_ID] /" $1
    fi
fi
